/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Log.Log;
import Log.Sesion;
import TicketAdmin.CreateTicket;
import TicketAdmin.NotStarted;
import TicketAdmin.TestDocumentacion;
import TicketAdmin.UserManager;
import javax.swing.JOptionPane;

/**
 *
 * @author IMX078856
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form adminmenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CreateTicketBoton = new javax.swing.JButton();
        BotonDocumentacion = new javax.swing.JButton();
        NotStartedBoton = new javax.swing.JButton();
        UserManagerBoton = new javax.swing.JButton();
        Usuariosystema = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Support_System/Menu");
        setLocation(new java.awt.Point(500, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                setusuario(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Menu Administrator");

        CreateTicketBoton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CreateTicketBoton.setText("Create Ticket");
        CreateTicketBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTicketBotonActionPerformed(evt);
            }
        });

        BotonDocumentacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonDocumentacion.setText("Documentation");
        BotonDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDocumentacionActionPerformed(evt);
            }
        });

        NotStartedBoton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NotStartedBoton.setText("Not Started");
        NotStartedBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotStartedBotonActionPerformed(evt);
            }
        });

        UserManagerBoton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UserManagerBoton.setText("User Manager");
        UserManagerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagerBotonActionPerformed(evt);
            }
        });

        Usuariosystema.setText("Usuario:");

        jButton1.setText("Log Off");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateTicketBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserManagerBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotStartedBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuariosystema, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotonDocumentacion, CreateTicketBoton, NotStartedBoton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Usuariosystema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateTicketBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotStartedBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserManagerBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDocumentacionActionPerformed

        TestDocumentacion ir = new TestDocumentacion();
        ir.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BotonDocumentacionActionPerformed

    private void CreateTicketBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTicketBotonActionPerformed

        CreateTicket ir = new CreateTicket();
        ir.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_CreateTicketBotonActionPerformed

    private void NotStartedBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotStartedBotonActionPerformed

        NotStarted ir = new NotStarted();
        ir.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_NotStartedBotonActionPerformed

    private void UserManagerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagerBotonActionPerformed
        UserManager ir = new UserManager();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserManagerBotonActionPerformed

    private void setusuario(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_setusuario
   String usuarioActual = Sesion.getUsuarioActual();
    Usuariosystema.setText("Usuario:" + usuarioActual+"👨");

    if (usuarioActual == null) {
        JOptionPane.showMessageDialog(null, "No hay un usuario conectado");
        this.dispose(); // Cierra la ventana actual
    } else {
        // Lógica adicional si el usuario no es null
    }

    }//GEN-LAST:event_setusuario

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Log ir = new Log();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDocumentacion;
    private javax.swing.JButton CreateTicketBoton;
    private javax.swing.JButton NotStartedBoton;
    private javax.swing.JButton UserManagerBoton;
    private javax.swing.JLabel Usuariosystema;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
